//
//  Localization.swift
//  Live FR / EN / AR switching + RTL. French strings are used as keys; EN/AR
//  translations live in the table below (missing keys fall back to French).
//

import Foundation
import SwiftUI

enum AppLang: String, CaseIterable, Identifiable {
    case fr, en, ar
    var id: String { rawValue }
    var label: String { self == .fr ? "Français" : (self == .en ? "English" : "العربية") }
    var isRTL: Bool { self == .ar }
}

final class LanguageManager: ObservableObject {
    @Published var lang: AppLang {
        didSet { Loc.current = lang; UserDefaults.standard.set(lang.rawValue, forKey: "appLang") }
    }
    init() {
        let saved = UserDefaults.standard.string(forKey: "appLang").flatMap(AppLang.init(rawValue:)) ?? .fr
        lang = saved
        Loc.current = saved
    }
}

func L(_ key: String) -> String { Loc.t(key) }

enum Loc {
    static var current: AppLang = .fr
    static func t(_ key: String) -> String { table[current]?[key] ?? key }

    static let table: [AppLang: [String: String]] = [
        .en: [
            "Accueil": "Home", "Horaires": "Schedules", "Billets": "Tickets",
            "Suivi": "Tracking", "Carte": "Card", "Le Maroc à grande vitesse": "Morocco at high speed",
            "Où allez-vous,": "Where to,", "Rechercher mon train": "Search trains", "Prochains départs": "Next departures",
            "Destinations populaires": "Popular destinations", "Mes trajets": "My routes", "Trajets récents": "Recent routes",
            "Enregistrer": "Save", "Enregistré": "Saved", "Départ": "From",
            "Arrivée": "To", "Date": "Date", "Voyageurs": "Passengers",
            "Aller-retour": "Round trip", "Aller simple": "One way", "2ᵉ Confort": "2nd Comfort",
            "1ʳᵉ Prestige": "1st Prestige", "Adulte": "Adult", "Enfant": "Child",
            "Senior": "Senior", "Suivant": "Next", "Commencer": "Get started",
            "Passer": "Skip", "Votre billet, dans votre poche": "Your ticket, in your pocket", "Suivez votre train en direct": "Track your train live",
            "Réservez Al Boraq, Al Atlas et TNR en quelques secondes, partout au Royaume.": "Book Al Boraq, Al Atlas and TNR in seconds, anywhere in the Kingdom.", "E-billet avec QR code, choix du siège et carte de réduction. Sans file, sans papier.": "E-ticket with QR code, seat choice and discount card. No queue, no paper.", "Position en temps réel, quai, et rappel avant le départ.": "Real-time position, platform, and a reminder before departure.",
            "Connexion": "Sign in", "Inscription": "Sign up", "Connectez-vous pour continuer": "Sign in to continue",
            "Créez votre compte voyageur": "Create your traveler account", "Nom complet": "Full name", "E-mail": "Email",
            "Mot de passe": "Password", "Se connecter": "Sign in", "Créer mon compte": "Create account",
            "Ma carte": "My card", "points fidélité": "loyalty points", "Se déconnecter": "Sign out",
            "Mes reçus": "My receipts", "Mes avantages": "My rewards", "Mon profil": "My profile", "Notifications": "Notifications",
            "Aide & contact": "Help & contact", "Réglages": "Settings", "Langue": "Language",
            "Réessayer": "Retry", "Annuler": "Cancel", "Voyages": "Voyages",
            "Voyagez plus, payez moins": "Travel more, pay less", "Compte": "Account", "Confidentialité": "Privacy",
            "Changer le mot de passe": "Change password", "Mot de passe actuel": "Current password", "Nouveau mot de passe": "New password",
            "Supprimer mon compte": "Delete my account", "Politique de confidentialité": "Privacy policy", "Conditions générales": "Terms & conditions",
            "Mes billets": "My tickets", "Billet": "Ticket", "Me rappeler": "Remind me",
            "Échanger": "Exchange", "Récapitulatif": "Summary", "Payer": "Pay",
            "Choisir le siège": "Choose seat", "Classe": "Class", "Total": "Total",
            "Heure": "Time", "Prix": "Price", "Durée": "Duration",
            "Suivi en direct": "Live tracking", "EN VOYAGE": "ON BOARD", "vitesse": "speed",
            "À l'heure": "On time", "Arrivée ": "Arrival ", "Aucun voyage en cours": "No trip in progress",
            "Réservez un trajet pour le suivre ici.": "Book a trip to track it here.", "Récapitulatif ": "Summary ", "Réservation confirmée !": "Booking confirmed!",
            "Voir mes billets": "View my tickets", "Aucun billet": "No tickets", "Annuler & rembourser": "Cancel & refund",
            "Choisissez votre retour": "Choose your return", "Aucun train pour cette date.": "No train for this date.", "Choisissez votre place": "Choose your seat",
            "Confirmer": "Confirm", "Libre": "Free", "Occupé": "Taken",
            "Choisi": "Selected", "Voyageur": "Passenger", "Nom du voyageur": "Passenger name",
            "À SAVOIR": "GOOD TO KNOW", "Retour": "Return", "Place": "Seat",
            "Sécurité": "Security",
            "Verrouiller avec %@": "Lock with %@",
            "Demander l'authentification à l'ouverture": "Require authentication on open",
            "Autorisation": "Permission", "Activées": "On",
            "Refusées — activez-les dans Réglages": "Denied — enable in Settings",
            "Non configurées": "Not set up", "Activer": "Enable", "Réglages iOS": "iOS Settings",
            "Alertes trafic": "Service alerts",
            "Perturbations et retards sur vos lignes": "Disruptions and delays on your lines",
            "Rappel de départ": "Departure reminder",
            "Me prévenir avant le départ": "Notify me before departure",
            "Délai du rappel automatique": "Automatic reminder lead time",
            "Délai": "Lead time", "%d min": "%d min",
            "Application verrouillée": "App locked", "Déverrouiller avec %@": "Unlock with %@",
            "Déverrouillez vos billets": "Unlock your tickets", "Code": "Passcode",
            "ou": "or", "Continuer avec Google": "Continue with Google",
            "Retard": "Delay", "Trafic perturbé": "Service disruption",
            "Train arrêté": "Train stopped", "ARRÊTÉ": "STOPPED",
            "Mode hors-ligne · vos billets restent accessibles": "Offline · your tickets stay available",
            "À propos": "About", "Contacter le support": "Contact support", "Version": "Version",
            "Itinéraire": "Route", "Agrandir": "Expand", "Centrer sur le train": "Center on train",
            "E-mail vérifié !": "Email verified!", "Votre compte est prêt.": "Your account is ready.",
            "Bienvenue": "Welcome", "Votre voyage commence ici.": "Your journey starts here.",
            "voyageur": "traveler",
            "Bienvenue à bord": "Welcome aboard",
            "Réservez vos trains à grande vitesse en quelques secondes.": "Book your high-speed trains in seconds.",
            "ARRIVÉ": "ARRIVED", "À QUAI": "AT PLATFORM", "Arrivé": "Arrived", "Départ dans": "Departs in",
            "Mode test · aucun argent réel": "Test mode · no real money", "Traitement…": "Processing…",
            "3-D Secure…": "3-D Secure…", "Cartes de test": "Test cards",
            "Toucher pour remplir": "Tap to fill", "Approuvée": "Approved", "Refusée": "Declined",
            "Fonds insuffisants": "Insufficient funds", "3-D Secure": "3-D Secure",
            "Numéro de carte": "Card number", "Enregistrer cette carte": "Save this card",
            "Mes cartes": "My cards", "Utiliser une autre carte": "Use another card",
            "Supprimer": "Delete", "Confirmez le paiement Apple Pay": "Confirm the Apple Pay payment",
            "Télécharger le billet": "Download ticket", "ALLER": "OUTBOUND", "RETOUR": "RETURN",
            "vérifiée": "verified", "Vérifiée": "Verified",
            "Lier une carte de réduction": "Link a discount card",
            "Liez votre carte de réduction ONCF pour appliquer vos tarifs réduits et cumuler des points.": "Link your ONCF discount card to apply reduced fares and earn points.",
            "Type de carte": "Card type", "Nom du titulaire": "Cardholder name",
            "Vérifier & lier": "Verify & link", "Vérification…": "Verifying…",
            "Vérification échouée. Vérifiez le numéro et le nom.": "Verification failed. Check the number and name.",
            "Carte vérifiée": "Card verified",
            "La réduction s'applique automatiquement à vos réservations.": "The discount applies automatically to your bookings.",
            "Fidélité liée": "Loyalty linked",
            "Vos points fidélité sont crédités sur cette carte (×1,5).": "Your loyalty points are credited to this card (×1.5).",
            "Vos points fidélité sont crédités sur cette carte.": "Your loyalty points are credited to this card.",
            "Supprimer la carte": "Remove card", "Compte & cartes": "Account & cards",
            "Réglages & aide": "Settings & help", "Carte de réduction": "Discount card",
            "La ville rouge": "The red city", "La porte du nord": "Gateway to the north",
            "La cité impériale": "The imperial city", "La métropole": "The metropolis",
            "Mot de passe oublié ?": "Forgot password?", "Mot de passe oublié": "Forgot password",
            "Fermer": "Close", "Envoyer le code": "Send code",
            "Mode démo — code de vérification": "Demo mode — verification code",
            "Code de vérification": "Verification code", "Vérifier": "Verify",
            "Enregistrement…": "Saving…", "Réinitialiser": "Reset",
            "Mot de passe mis à jour": "Password updated", "Retour à la connexion": "Back to sign in",
            "Adresse e-mail invalide.": "Invalid e-mail address.",
            "Aucun compte avec cet e-mail.": "No account with that e-mail.",
            "Code incorrect.": "Incorrect code.",
            "Le mot de passe doit faire au moins 6 caractères.": "Password must be at least 6 characters.",
            "Réinitialiser le mot de passe": "Reset password", "Entrez le code": "Enter the code",
            "Terminé": "Done", "Vous pouvez maintenant vous connecter.": "You can now sign in.",
            "Saisissez l'e-mail de votre compte, nous vous enverrons un code.": "Enter your account e-mail and we'll send you a code.",
            "Saisissez le code de vérification à 6 chiffres.": "Enter the 6-digit verification code.",
            "Choisissez un nouveau mot de passe (6 caractères minimum).": "Choose a new password (6 characters minimum).",
            "Saisissez le code reçu puis choisissez un nouveau mot de passe.": "Enter the code you received, then choose a new password.",
            "Un code a été envoyé à votre e-mail.": "A code has been sent to your e-mail.",
            "Créez un compte — vérification par e-mail.": "Create an account — e-mail verification.",
            "Vérifiez votre e-mail": "Verify your e-mail",
            "Saisissez le code à 6 chiffres envoyé à %@.": "Enter the 6-digit code sent to %@.",
            "Confirmer mon compte": "Confirm my account", "Confirmer l'e-mail": "Confirm e-mail",
            "Vérifiez aussi vos spams. Le code peut prendre une minute.": "Check your spam too. The code can take a minute.",
            "Comment ça marche": "How it works",
            "Cherchez votre trajet": "Search your trip",
            "Choisissez départ, arrivée et date sur l'accueil, puis lancez la recherche.": "Pick departure, arrival and date on the home screen, then search.",
            "Réservez en quelques secondes": "Book in seconds",
            "Sélectionnez un train, vos voyageurs et votre place, puis payez en toute sécurité.": "Pick a train, your passengers and seat, then pay securely.",
            "Votre e-billet": "Your e-ticket",
            "Retrouvez votre billet avec QR code dans l'onglet Billets, et téléchargez-le en PDF.": "Find your QR-code ticket in the Tickets tab, and download it as PDF.",
            "Suivez votre train": "Track your train",
            "Dans Suivi, voyez la position de votre train en direct et votre distance par rapport à lui.": "In Tracking, see your train's live position and how far you are from it.",
            "Carte & fidélité": "Card & loyalty",
            "Gérez votre profil, votre carte de réduction et vos points dans l'onglet Carte.": "Manage your profile, discount card and points in the Card tab.",
            "À %@ de votre train": "%@ from your train",
            "Ajouter un voyageur": "Add a passenger", "Retirer un voyageur": "Remove a passenger",
            "Prochain arrêt": "Next stop", "Arrêt %d min": "%d min stop",
            "Retard sur votre train": "Your train is delayed",
            "Perturbation sur votre ligne": "Disruption on your line",
            "retard d'environ %d min": "delay of about %d min",
            "À venir": "Upcoming", "Passés": "Past",
            "Gare la plus proche · %@ de vous": "Nearest station · %@ from you",
            "Ajouter à Apple Wallet": "Add to Apple Wallet",
            "VOITURE": "COACH", "PLACE": "SEAT", "CLASSE": "CLASS", "VOYAGEURS": "PASSENGERS",
            "EMBARQUEMENT": "BOARDING", "MONTANT À PAYER": "AMOUNT TO PAY",
            "ALLER-RETOUR": "ROUND TRIP", "ALLER SIMPLE": "ONE WAY",
            "Expiration": "Expiry", "CVV": "CVV", "ou par carte": "or by card",
            "Chiffré · 3-D Secure": "Encrypted · 3-D Secure", "Paiement": "Payment",
            "Voit. %d · %@": "Coach %d · %@", "Rappel activé": "Reminder on",
            "Réservez un voyage depuis l'accueil.": "Book a trip from the home screen.",
            "Recherche des trains…": "Searching trains…",
            "Annuler ce billet ?": "Cancel this ticket?", "Garder mon billet": "Keep my ticket",
            "Annuler · remboursé %@": "Cancel · refunded %@", "Annuler (non remboursé)": "Cancel (no refund)",
            "Présentez-vous 20 min avant le départ, muni d'une pièce d'identité valide. Billet nominatif et non cessible · échange & annulation gratuits jusqu'à 1h avant le départ.": "Arrive 20 min before departure with valid ID. Personal, non-transferable ticket · free exchange & cancellation up to 1h before departure.",
            "Numéro de carte invalide.": "Invalid card number.",
            "Date d'expiration invalide (MM/AA).": "Invalid expiry date (MM/YY).",
            "Code CVV invalide.": "Invalid CVV.", "Paiement échoué.": "Payment failed.",
            "Paiement refusé par la banque.": "Payment declined by the bank.", "Paiement annulé.": "Payment cancelled.",
            "Fonds insuffisants sur la carte.": "Insufficient funds on the card.", "Carte expirée.": "Card expired.",
            "Échec de l'authentification 3-D Secure.": "3-D Secure authentication failed.",
            "Connexion au service de paiement impossible.": "Couldn't reach the payment service.",
            "Connexion au service impossible : %@": "Couldn't reach the service: %@",
            "E-mail ou mot de passe incorrect.": "Incorrect e-mail or password.",
            "Un compte existe déjà avec cet e-mail.": "An account already exists with this e-mail.",
            "Apple Wallet nécessite un certificat Pass Type ID et un service de signature côté serveur.": "Apple Wallet needs a Pass Type ID certificate and a server-side signing service.",
            "Le pass reçu est invalide.": "The received pass is invalid.",
            "Voie": "Platform", "Votre gare approche": "Your station is approaching",
            "Préparez-vous à descendre à %@ · voiture %d, place %@.": "Get ready to alight at %@ · coach %d, seat %@.",
            "Erreur": "Error"
        ],
        .ar: [
            "Accueil": "الرئيسية", "Horaires": "المواعيد", "Billets": "التذاكر",
            "Suivi": "التتبع", "Carte": "البطاقة", "Le Maroc à grande vitesse": "المغرب بسرعة فائقة",
            "Où allez-vous,": "إلى أين,", "Rechercher mon train": "ابحث عن قطاري", "Prochains départs": "الرحلات القادمة",
            "Destinations populaires": "وجهات مشهورة", "Mes trajets": "رحلاتي", "Trajets récents": "الرحلات الأخيرة",
            "Enregistrer": "حفظ", "Enregistré": "محفوظ", "Départ": "المغادرة",
            "Arrivée": "الوصول", "Date": "التاريخ", "Voyageurs": "المسافرون",
            "Aller-retour": "ذهاب وإياب", "Aller simple": "ذهاب فقط", "2ᵉ Confort": "الدرجة الثانية",
            "1ʳᵉ Prestige": "الدرجة الأولى", "Adulte": "بالغ", "Enfant": "طفل",
            "Senior": "مسنّ", "Suivant": "التالي", "Commencer": "ابدأ",
            "Passer": "تخطٍّ", "Votre billet, dans votre poche": "تذكرتك في جيبك", "Suivez votre train en direct": "تتبّع قطارك مباشرة",
            "Réservez Al Boraq, Al Atlas et TNR en quelques secondes, partout au Royaume.": "احجز البراق والأطلس و TNR في ثوانٍ، في كل أنحاء المملكة.", "E-billet avec QR code, choix du siège et carte de réduction. Sans file, sans papier.": "تذكرة إلكترونية مع رمز QR واختيار المقعد وبطاقة التخفيض. بدون طابور وبدون ورق.", "Position en temps réel, quai, et rappel avant le départ.": "الموقع في الوقت الفعلي، الرصيف، وتذكير قبل المغادرة.",
            "Connexion": "تسجيل الدخول", "Inscription": "إنشاء حساب", "Connectez-vous pour continuer": "سجّل الدخول للمتابعة",
            "Créez votre compte voyageur": "أنشئ حساب المسافر", "Nom complet": "الاسم الكامل", "E-mail": "البريد الإلكتروني",
            "Mot de passe": "كلمة المرور", "Se connecter": "تسجيل الدخول", "Créer mon compte": "إنشاء الحساب",
            "Ma carte": "بطاقتي", "points fidélité": "نقاط الولاء", "Se déconnecter": "تسجيل الخروج",
            "Mes reçus": "إيصالاتي", "Mes avantages": "مزاياي", "Mon profil": "ملفي الشخصي", "Notifications": "الإشعارات",
            "Aide & contact": "المساعدة والتواصل", "Réglages": "الإعدادات", "Langue": "اللغة",
            "Réessayer": "إعادة المحاولة", "Annuler": "إلغاء", "Voyages": "Voyages",
            "Voyagez plus, payez moins": "سافر أكثر وادفع أقل", "Compte": "الحساب", "Confidentialité": "الخصوصية",
            "Changer le mot de passe": "تغيير كلمة المرور", "Mot de passe actuel": "كلمة المرور الحالية", "Nouveau mot de passe": "كلمة المرور الجديدة",
            "Supprimer mon compte": "حذف حسابي", "Politique de confidentialité": "سياسة الخصوصية", "Conditions générales": "الشروط العامة",
            "Mes billets": "تذاكري", "Billet": "التذكرة", "Me rappeler": "ذكّرني",
            "Échanger": "استبدال", "Récapitulatif": "الملخص", "Payer": "ادفع",
            "Choisir le siège": "اختر المقعد", "Classe": "الدرجة", "Total": "المجموع",
            "Heure": "الوقت", "Prix": "السعر", "Durée": "المدة",
            "Suivi en direct": "التتبع المباشر", "EN VOYAGE": "في الرحلة", "vitesse": "السرعة",
            "À l'heure": "في الموعد", "Aucun voyage en cours": "لا توجد رحلة جارية", "Réservez un trajet pour le suivre ici.": "احجز رحلة لتتبّعها هنا.",
            "Réservation confirmée !": "تم تأكيد الحجز!", "Voir mes billets": "عرض تذاكري", "Aucun billet": "لا توجد تذاكر",
            "Annuler & rembourser": "إلغاء واسترداد", "Choisissez votre retour": "اختر رحلة العودة", "Aucun train pour cette date.": "لا يوجد قطار لهذا التاريخ.",
            "Choisissez votre place": "اختر مقعدك", "Confirmer": "تأكيد", "Libre": "متاح",
            "Occupé": "محجوز", "Choisi": "مختار", "Voyageur": "مسافر",
            "Nom du voyageur": "اسم المسافر", "À SAVOIR": "معلومة مهمة", "Retour": "العودة",
            "Place": "مقعد",
            "Sécurité": "الأمان",
            "Verrouiller avec %@": "القفل بواسطة %@",
            "Demander l'authentification à l'ouverture": "طلب المصادقة عند الفتح",
            "Autorisation": "الإذن", "Activées": "مفعّلة",
            "Refusées — activez-les dans Réglages": "مرفوضة — فعّلها من الإعدادات",
            "Non configurées": "غير مهيّأة", "Activer": "تفعيل", "Réglages iOS": "إعدادات iOS",
            "Alertes trafic": "تنبيهات الحركة",
            "Perturbations et retards sur vos lignes": "اضطرابات وتأخيرات على خطوطك",
            "Rappel de départ": "تذكير بالمغادرة",
            "Me prévenir avant le départ": "نبّهني قبل المغادرة",
            "Délai du rappel automatique": "مهلة التذكير التلقائي",
            "Délai": "المهلة", "%d min": "%d دقيقة",
            "Application verrouillée": "التطبيق مقفل", "Déverrouiller avec %@": "افتح القفل بواسطة %@",
            "Déverrouillez vos billets": "افتح قفل تذاكرك", "Code": "رمز",
            "ou": "أو", "Continuer avec Google": "المتابعة باستخدام Google",
            "Retard": "تأخير", "Trafic perturbé": "اضطراب في الحركة",
            "Train arrêté": "القطار متوقف", "ARRÊTÉ": "متوقف",
            "Mode hors-ligne · vos billets restent accessibles": "غير متصل · تذاكرك تبقى متاحة",
            "À propos": "حول", "Contacter le support": "تواصل مع الدعم", "Version": "الإصدار",
            "Itinéraire": "المسار", "Agrandir": "تكبير", "Centrer sur le train": "توسيط على القطار",
            "E-mail vérifié !": "تم التحقق من البريد!", "Votre compte est prêt.": "حسابك جاهز.",
            "Bienvenue": "مرحبًا", "Votre voyage commence ici.": "رحلتك تبدأ من هنا.",
            "voyageur": "مسافر",
            "Bienvenue à bord": "مرحبًا بك على متن القطار",
            "Réservez vos trains à grande vitesse en quelques secondes.": "احجز قطاراتك فائقة السرعة في ثوانٍ.",
            "ARRIVÉ": "وصل", "À QUAI": "على الرصيف", "Arrivé": "وصل", "Départ dans": "المغادرة بعد",
            "Mode test · aucun argent réel": "وضع الاختبار · بدون مال حقيقي", "Traitement…": "جارٍ المعالجة…",
            "3-D Secure…": "3-D Secure…", "Cartes de test": "بطاقات الاختبار",
            "Toucher pour remplir": "اضغط للتعبئة", "Approuvée": "مقبولة", "Refusée": "مرفوضة",
            "Fonds insuffisants": "رصيد غير كافٍ", "3-D Secure": "3-D Secure",
            "Numéro de carte": "رقم البطاقة", "Enregistrer cette carte": "احفظ هذه البطاقة",
            "Mes cartes": "بطاقاتي", "Utiliser une autre carte": "استخدام بطاقة أخرى",
            "Supprimer": "حذف", "Confirmez le paiement Apple Pay": "أكّد الدفع عبر Apple Pay",
            "Télécharger le billet": "تحميل التذكرة", "ALLER": "ذهاب", "RETOUR": "إياب",
            "vérifiée": "مُوثَّقة", "Vérifiée": "مُوثَّقة",
            "Lier une carte de réduction": "ربط بطاقة تخفيض",
            "Liez votre carte de réduction ONCF pour appliquer vos tarifs réduits et cumuler des points.": "اربط بطاقة التخفيض ONCF للاستفادة من الأسعار المخفّضة وجمع النقاط.",
            "Type de carte": "نوع البطاقة", "Nom du titulaire": "اسم حامل البطاقة",
            "Vérifier & lier": "تحقّق واربط", "Vérification…": "جارٍ التحقّق…",
            "Vérification échouée. Vérifiez le numéro et le nom.": "فشل التحقّق. تحقّق من الرقم والاسم.",
            "Carte vérifiée": "تم التحقّق من البطاقة",
            "La réduction s'applique automatiquement à vos réservations.": "يُطبَّق التخفيض تلقائيًا على حجوزاتك.",
            "Fidélité liée": "الولاء مرتبط",
            "Vos points fidélité sont crédités sur cette carte (×1,5).": "تُضاف نقاط الولاء إلى هذه البطاقة (×1.5).",
            "Vos points fidélité sont crédités sur cette carte.": "تُضاف نقاط الولاء إلى هذه البطاقة.",
            "Supprimer la carte": "حذف البطاقة", "Compte & cartes": "الحساب والبطاقات",
            "Réglages & aide": "الإعدادات والمساعدة", "Carte de réduction": "بطاقة التخفيض",
            "La ville rouge": "المدينة الحمراء", "La porte du nord": "بوابة الشمال",
            "La cité impériale": "المدينة الإمبراطورية", "La métropole": "العاصمة الاقتصادية",
            "Mot de passe oublié ?": "نسيت كلمة المرور؟", "Mot de passe oublié": "نسيت كلمة المرور",
            "Fermer": "إغلاق", "Envoyer le code": "إرسال الرمز",
            "Mode démo — code de vérification": "وضع تجريبي — رمز التحقّق",
            "Code de vérification": "رمز التحقّق", "Vérifier": "تحقّق",
            "Enregistrement…": "جارٍ الحفظ…", "Réinitialiser": "إعادة تعيين",
            "Mot de passe mis à jour": "تم تحديث كلمة المرور", "Retour à la connexion": "العودة لتسجيل الدخول",
            "Adresse e-mail invalide.": "عنوان بريد إلكتروني غير صالح.",
            "Aucun compte avec cet e-mail.": "لا يوجد حساب بهذا البريد الإلكتروني.",
            "Code incorrect.": "رمز غير صحيح.",
            "Le mot de passe doit faire au moins 6 caractères.": "يجب أن تتكوّن كلمة المرور من 6 أحرف على الأقل.",
            "Réinitialiser le mot de passe": "إعادة تعيين كلمة المرور", "Entrez le code": "أدخل الرمز",
            "Terminé": "تم", "Vous pouvez maintenant vous connecter.": "يمكنك الآن تسجيل الدخول.",
            "Saisissez l'e-mail de votre compte, nous vous enverrons un code.": "أدخل بريد حسابك وسنرسل لك رمزًا.",
            "Saisissez le code de vérification à 6 chiffres.": "أدخل رمز التحقّق المكوّن من 6 أرقام.",
            "Choisissez un nouveau mot de passe (6 caractères minimum).": "اختر كلمة مرور جديدة (6 أحرف على الأقل).",
            "Saisissez le code reçu puis choisissez un nouveau mot de passe.": "أدخل الرمز الذي وصلك ثم اختر كلمة مرور جديدة.",
            "Un code a été envoyé à votre e-mail.": "تم إرسال رمز إلى بريدك الإلكتروني.",
            "Créez un compte — vérification par e-mail.": "أنشئ حسابًا — التحقّق عبر البريد الإلكتروني.",
            "Vérifiez votre e-mail": "تحقّق من بريدك الإلكتروني",
            "Saisissez le code à 6 chiffres envoyé à %@.": "أدخل الرمز المكوّن من 6 أرقام المُرسَل إلى %@.",
            "Confirmer mon compte": "تأكيد حسابي", "Confirmer l'e-mail": "تأكيد البريد",
            "Vérifiez aussi vos spams. Le code peut prendre une minute.": "تحقّق أيضًا من البريد المزعج. قد يستغرق الرمز دقيقة.",
            "Comment ça marche": "كيف يعمل التطبيق",
            "Cherchez votre trajet": "ابحث عن رحلتك",
            "Choisissez départ, arrivée et date sur l'accueil, puis lancez la recherche.": "اختر المغادرة والوصول والتاريخ في الرئيسية، ثم ابدأ البحث.",
            "Réservez en quelques secondes": "احجز في ثوانٍ",
            "Sélectionnez un train, vos voyageurs et votre place, puis payez en toute sécurité.": "اختر قطارًا ومسافريك ومقعدك، ثم ادفع بأمان.",
            "Votre e-billet": "تذكرتك الإلكترونية",
            "Retrouvez votre billet avec QR code dans l'onglet Billets, et téléchargez-le en PDF.": "اعثر على تذكرتك برمز QR في تبويب التذاكر، وحمّلها بصيغة PDF.",
            "Suivez votre train": "تتبّع قطارك",
            "Dans Suivi, voyez la position de votre train en direct et votre distance par rapport à lui.": "في التتبّع، شاهد موقع قطارك مباشرةً والمسافة بينك وبينه.",
            "Carte & fidélité": "البطاقة والولاء",
            "Gérez votre profil, votre carte de réduction et vos points dans l'onglet Carte.": "أدِر ملفك وبطاقة التخفيض ونقاطك في تبويب البطاقة.",
            "À %@ de votre train": "%@ من قطارك",
            "Ajouter un voyageur": "إضافة مسافر", "Retirer un voyageur": "إزالة مسافر",
            "Prochain arrêt": "المحطة التالية", "Arrêt %d min": "توقّف %d دقيقة",
            "Retard sur votre train": "تأخير في قطارك",
            "Perturbation sur votre ligne": "اضطراب في خطك",
            "retard d'environ %d min": "تأخير بحوالي %d دقيقة",
            "À venir": "القادمة", "Passés": "السابقة",
            "Gare la plus proche · %@ de vous": "أقرب محطة · %@ منك",
            "Ajouter à Apple Wallet": "أضِف إلى Apple Wallet",
            "VOITURE": "العربة", "PLACE": "المقعد", "CLASSE": "الدرجة", "VOYAGEURS": "المسافرون",
            "EMBARQUEMENT": "الصعود", "MONTANT À PAYER": "المبلغ المطلوب",
            "ALLER-RETOUR": "ذهاب وإياب", "ALLER SIMPLE": "ذهاب فقط",
            "Expiration": "انتهاء", "CVV": "CVV", "ou par carte": "أو بالبطاقة",
            "Chiffré · 3-D Secure": "مشفّر · 3-D Secure", "Paiement": "الدفع",
            "Voit. %d · %@": "العربة %d · %@", "Rappel activé": "التذكير مُفعّل",
            "Réservez un voyage depuis l'accueil.": "احجز رحلة من الصفحة الرئيسية.",
            "Recherche des trains…": "جارٍ البحث عن القطارات…",
            "Annuler ce billet ?": "إلغاء هذه التذكرة؟", "Garder mon billet": "الاحتفاظ بتذكرتي",
            "Annuler · remboursé %@": "إلغاء · استُرد %@", "Annuler (non remboursé)": "إلغاء (دون استرداد)",
            "Présentez-vous 20 min avant le départ, muni d'une pièce d'identité valide. Billet nominatif et non cessible · échange & annulation gratuits jusqu'à 1h avant le départ.": "احضر قبل 20 دقيقة من المغادرة ومعك بطاقة هوية صالحة. التذكرة اسمية وغير قابلة للتحويل · التغيير والإلغاء مجاني حتى ساعة قبل المغادرة.",
            "Numéro de carte invalide.": "رقم بطاقة غير صالح.",
            "Date d'expiration invalide (MM/AA).": "تاريخ انتهاء غير صالح (شش/سس).",
            "Code CVV invalide.": "رمز CVV غير صالح.", "Paiement échoué.": "فشل الدفع.",
            "Paiement refusé par la banque.": "رفض البنك الدفع.", "Paiement annulé.": "تم إلغاء الدفع.",
            "Fonds insuffisants sur la carte.": "رصيد غير كافٍ في البطاقة.", "Carte expirée.": "البطاقة منتهية الصلاحية.",
            "Échec de l'authentification 3-D Secure.": "فشل التحقّق 3-D Secure.",
            "Connexion au service de paiement impossible.": "تعذّر الاتصال بخدمة الدفع.",
            "Connexion au service impossible : %@": "تعذّر الاتصال بالخدمة: %@",
            "E-mail ou mot de passe incorrect.": "البريد الإلكتروني أو كلمة المرور غير صحيحة.",
            "Un compte existe déjà avec cet e-mail.": "يوجد حساب بالفعل بهذا البريد الإلكتروني.",
            "Apple Wallet nécessite un certificat Pass Type ID et un service de signature côté serveur.": "يتطلّب Apple Wallet شهادة Pass Type ID وخدمة توقيع من جهة الخادم.",
            "Le pass reçu est invalide.": "البطاقة المستلمة غير صالحة.",
            "Voie": "الرصيف", "Votre gare approche": "محطتك تقترب",
            "Préparez-vous à descendre à %@ · voiture %d, place %@.": "استعد للنزول في %@ · العربة %d، المقعد %@.",
            "Erreur": "خطأ"
        ]
    ]
}

extension TripKind { var localized: String { L(rawValue) } }
extension FareClass { var localized: String { L(rawValue) } }
extension PassengerType { var localized: String { L(rawValue) } }
